import '../src/static/images/wall/wall.gif'
export default{
    canvas:{
        width:900,
        height:600
    },
    models:{
        width:30,
        height:30,
    },
    images:{
        straw:'../src/static/images/straw/straw.png',
        wall:'../src/static/images/wall/wall.gif',
        water:'../src/static/images/water/water.gif',
        steels:'../src/static/images/wall/steels.gif',
        tankBottom:'../src/static/images/tank/bottom.gif',
        tankTop:'../src/static/images/tank/top.gif',
        tankLeft:'../src/static/images/tank/left.gif',
        tankRight:'../src/static/images/tank/right.gif',
        bullet:'../src/static/images/bullet/bullet.jpg',
        boss:'../src/static/images/boss/boss.png',
        playerTop:'../src/static/images/player/top.gif',
        playerBottom:'../src/static/images/player/bottom.gif',
        playerLeft:'../src/static/images/player/left.gif',
        playerRight:'../src/static/images/player/right.gif'
    },
    straw:{
        image:'../src/static/images/straw/straw.png',
        num:150
    },
    wall:{
        image:'../src/static/images/wall/wall.gif',
        num:60
    },
    water:{
        image:'../src/static/images/water/water.gif',
        num:40
    },
    steels:{
       image:'../src/static/images/wall/steels.gif',
       num:50
    },
    tank:{
        image:'../src/static/images/tank/bottom.gif',
        num:20
    },
    bullet:{
        image:'../src/static/images/bullet/bullet.jpg',
       num:10
    },
    boss:{
        image:'../src/static/images/boss/boss.png',
        num:1
    },
    timeout:30
}